operations:
  view:
    - type: web
      impl: index.html
actions: actions
web: web-src
runtimeManifest:
  packages:
    dx-excshell-1:
      license: Apache-2.0
      actions:
        generic:
          function: actions/generic/index.cjs
          web: 'yes'
          runtime: nodejs:16
          inputs:
            LOG_LEVEL: debug
          annotations:
            require-adobe-auth: false
            final: true
        md-to-docx:
          function: actions/md-to-docx/index.cjs
          web: 'yes'
          runtime: nodejs:16
          inputs:
            LOG_LEVEL: debug
          annotations:
            require-adobe-auth: false
            final: true
        md-to-pdf:
          function: actions/md-to-pdf/index.cjs
          web: 'yes'
          runtime: nodejs:16
          inputs:
            LOG_LEVEL: debug
          annotations:
            require-adobe-auth: false
            final: true
        md-to-docx-info:
          function: actions/md-to-docx-info/index.cjs
          web: 'yes'
          runtime: nodejs:16
          inputs:
            LOG_LEVEL: debug
          annotations:
            require-adobe-auth: false
            final: true
        md-to-pdf-info:
          function: actions/md-to-pdf-info/index.cjs
          web: 'yes'
          runtime: nodejs:16
          inputs:
            LOG_LEVEL: debug
          annotations:
            require-adobe-auth: false
            final: true
